### ISSUE TITLE
Calling pydoc-markdown with `--render-toc` option causes an exception.

### ISSUE THREAD

**Issue by rcdtx** [NiklasRosenstein/pydoc-markdown#213]
**Environment**

- Pydoc-Markdown Version: v4.3.0
- Python Version: v3.9.5
- Operating System: fedora 34

- installed pydoc-markdown with pip in a clean venv.

**Describe the bug**
Calling pydoc-markdown with `--render-toc` option causes a TypeError exception.

command:
`pydoc-markdown -I . --render-toc`

error:
Traceback (most recent call last):
  File ".../bin/pydoc-markdown", line 8, in <module>
    sys.exit(cli())
  File ".../lib64/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File ".../lib64/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File ".../lib64/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib64/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File ".../lib64/python3.9/site-packages/pydoc_markdown/main.py", line 332, in cli
    pydocmd = session.load()
  File ".../lib64/python3.9/site-packages/pydoc_markdown/main.py", line 122, in load
    self._apply_overrides(config)
  File ".../lib64/python3.9/site-packages/pydoc_markdown/main.py", line 101, in _apply_overrides
    schema = dataclass_to_schema(type(config.renderer))
TypeError: dataclass_to_schema() missing 1 required positional argument: 'type_hint_adapter'

**Comment by NiklasRosenstein** [comment]
Thanks for reporting this, @rcdtx! Fixed in 4.3.1 :)
