### ISSUE TITLE
No module named 'docstring_parser'

### ISSUE THREAD

**Issue by stevedefazio** [NiklasRosenstein/pydoc-markdown#281]
I ran `pip install pydoc-markdown` and then tried the following, which resulted in an error. I haven't found any troubleshooting tips in the docs, so I'm looking for guidance on what I may be missing.

```
(fig-common) PS C:\users\udyj\git\fig-common> pydoc-markdown -m fig_common > docs.txt
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\UDYJ\git\fig-common\Scripts\pydoc-markdown.exe\__main__.py", line 5, in <module>
  File "c:\users\udyj\git\fig-common\lib\site-packages\pydoc_markdown\__init__.py", line 42, in <module>
    from pydoc_markdown.contrib.processors.smart import SmartProcessor
  File "c:\users\udyj\git\fig-common\lib\site-packages\pydoc_markdown\contrib\processors\smart.py", line 27, in <module>
    from pydoc_markdown.contrib.processors.google import GoogleProcessor
  File "c:\users\udyj\git\fig-common\lib\site-packages\pydoc_markdown\contrib\processors\google.py", line 28, in <module>
    from pydoc_markdown.contrib.processors.sphinx import generate_sections_markdown
  File "c:\users\udyj\git\fig-common\lib\site-packages\pydoc_markdown\contrib\processors\sphinx.py", line 27, in <module>
    import docstring_parser
ModuleNotFoundError: No module named 'docstring_parser'
```

**Comment by NiklasRosenstein** [comment]
Are you sure nothing went wrong during the installation? Pydoc-markdown explicitly depends on this package.

https://github.com/NiklasRosenstein/pydoc-markdown/blob/3aa2fa94f514ee827992e4145a23e1260b5a4efd/pyproject.toml#L29

**Comment by NiklasRosenstein** [comment]
Closing due to no response.
