### ISSUE TITLE
Error: myfile is not a package

### ISSUE THREAD

**Issue by Kamik423** [NiklasRosenstein/pydoc-markdown#47]
on running (simple) for `parser.py`

```python
Building index...
Traceback (most recent call last):
  File "/usr/local/bin/pydocmd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/pydocmd/__main__.py", line 202, in main
    add_sections(doc, args.subargs)
  File "/usr/local/lib/python3.6/site-packages/pydocmd/__main__.py", line 168, in add_sections
    [add_sections(doc, x, depth) for x in object_names]
  File "/usr/local/lib/python3.6/site-packages/pydocmd/__main__.py", line 168, in <listcomp>
    [add_sections(doc, x, depth) for x in object_names]
  File "/usr/local/lib/python3.6/site-packages/pydocmd/__main__.py", line 190, in add_sections
    create_sections(object_names, 0)
  File "/usr/local/lib/python3.6/site-packages/pydocmd/__main__.py", line 186, in create_sections
    for sub in dir_object(name, sort_order):
  File "/usr/local/lib/python3.6/site-packages/pydocmd/imp.py", line 83, in dir_object
    obj = import_object(name)
  File "/usr/local/lib/python3.6/site-packages/pydocmd/imp.py", line 44, in import_object
    return import_object_with_scope(name)[0]
  File "/usr/local/lib/python3.6/site-packages/pydocmd/imp.py", line 73, in import_object_with_scope
    obj = scope = import_module(current_name)
  File "/usr/local/lib/python3.6/site-packages/pydocmd/imp.py", line 36, in import_module
    return __import__(name, fromlist=[''])
ModuleNotFoundError: No module named 'parser.py'; 'parser' is not a package
```

**Comment by Kamik423** [comment]
Sorry, my bad for not reading the docs. removed `.py`. cannot delete issue, just closing it.
