### ISSUE TITLE
ModuleNotFoundError: No module named, wrong name in __init__.py

### ISSUE THREAD

**Issue by aurelien-clu** [NiklasRosenstein/pydoc-markdown#73]
# Context

```bash
cd docs
pydocmd build
```

> ModuleNotFoundError: No module named 'my-project'

This error may not be explicit enough. (Or I am not knowledgeable enough :wink: )
This error comes from a wrong `__name__` inside the root `__init__.py`

Anyway, this issue is here to keep a trace of this problem for others and potentially get a more explanatory error. :smile: 

Directory structure:
- my-project
  - `my_project`
    - `__init__.py`
    - `some_module`
  - docs
  - `tests`

# Stacktrace

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/my-project/bin/pydocmd", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/__main__.py", line 234, in main
    add_sections(doc, object_names)
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/__main__.py", line 194, in add_sections
    [add_sections(doc, x, depth) for x in object_names]
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/__main__.py", line 194, in <listcomp>
    [add_sections(doc, x, depth) for x in object_names]
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/__main__.py", line 217, in add_sections
    create_sections(object_names, 0)
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/__main__.py", line 213, in create_sections
    for sub in dir_object(name, sort_order, need_docstrings):
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/imp.py", line 95, in dir_object
    obj = import_object(name)
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/imp.py", line 44, in import_object
    return import_object_with_scope(name)[0]
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/imp.py", line 64, in import_object_with_scope
    obj = import_module(current_name)
  File "/home/user/anaconda3/envs/my-project/lib/python3.6/site-packages/pydocmd/imp.py", line 36, in import_module
    return __import__(name, fromlist=[''])
ModuleNotFoundError: No module named 'my-project'
```

# init
`my_project/__init__.py`
```python
__name__ = "my-project"
```

# Corrected init

`my_project/__init__.py`
```python
__name__ = "my_project"
```

EDIT: added the command ran

**Comment by AuHau** [comment]
Just out of curiosity, why do you actually explicitly set the `__name__` variable?

**Comment by aurelien-clu** [comment]
I was not aware that it was define automatically :neutral_face: 

Feel free to close this :wink:

**Comment by AuHau** [comment]
Yeah, it is sort-of internal variable, which I would avoid to temper with as it might break things 😄

**Comment by NiklasRosenstein** [comment]
While setting `__name__` is definitely an anti-pattern, it is not going to be a problem in Pydoc-Markdown 3 as it will not actually import your module.
