### ISSUE TITLE
ImportError: No module named Enum.name when running pydocmd simple (python 2.7)

### ISSUE THREAD

**Issue by isthisthat** [NiklasRosenstein/pydoc-markdown#96]
Hello,
I've installed both packages Enum and enum34 (backport from python 3.4) but still get this message when I

    pydocmd simple class+ > doc.md

    Building index...
    Traceback (most recent call last):
    File "/illumina/thirdparty/python/python-2.7.5/bin/pydocmd", line 11, in <module>
        load_entry_point('pydoc-markdown==2.0.5', 'console_scripts', 'pydocmd')()
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/__main__.py", line 229, in main
        add_sections(doc, args.subargs)
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/__main__.py", line 194, in add_sections
        [add_sections(doc, x, depth) for x in object_names]
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/__main__.py", line 217, in add_sections
        create_sections(object_names, 0)
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/__main__.py", line 213, in create_sections
        for sub in dir_object(name, sort_order, need_docstrings):
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/imp.py", line 114, in dir_object
        if not (isinstance(value, type) and dir_object(name + '.' + key, sort_order, True)):
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/imp.py", line 102, in dir_object
        force_lazy_import(name)
     File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/imp.py", line 90, in force_lazy_import
         import_object(name + '.' + key)
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/imp.py", line 44, in import_object
        return import_object_with_scope(name)[0]
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/imp.py", line 73, in import_object_with_scope
        obj = scope = import_module(current_name)
    File "/illumina/thirdparty/python/python-2.7.5/lib/python2.7/site-packages/pydocmd/imp.py", line 36, in import_module
        return __import__(name, fromlist=[''])
    ImportError: No module named Enum.name

Thanks.

**Comment by NiklasRosenstein** [comment]
In

```
pydocmd simple class+ > doc.md
```

What did you substitute for `class`?

**Comment by NiklasRosenstein** [comment]
Closing due to lack of response.
